<ul class="breadcrumb">
    <?php foreach ($this->pages as $key => $page): ?>
        <li>
            <?php
            // if this isn't the last page, add a link and the separator:
            if ($key < count($this->pages) - 1):
            ?>
                <a href="<?= $page->getHref() ?>"> <?= $page->getLabel() ?> </a>
            <?php
            // otherwise, output name only
            else:
            ?>
                <?= $page->getLabel() ?>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>