<?php
// module/Client/view/client/client/add.phtml:

$title = 'Ajouter un client';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
// Ceci fournit le style de l'élément  nom:
$nom = $form->get('nom');
$nom->setAttribute('class', 'form-control');
$nom->setAttribute('placeholder', 'Nom du client');

// Ceci fournit le style de l'élément  prnom:
$prenom = $form->get('prenom');
$prenom->setAttribute('class', 'form-control');
$prenom->setAttribute('placeholder', 'Prénom');

$adresse = $form->get('adresse');
$adresse->setAttribute('class', 'form-control');
$adresse->setAttribute('placeholder', 'Adresse');

$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'Email');

$date_naissance = $form->get('date_naissance');
$date_naissance->setAttribute('class', 'form-control');
$date_naissance->setAttribute('placeholder', 'Date de naissance');

$sexe = $form->get('sexe');
$sexe->setAttribute('class', 'form-control');
$sexe->setAttribute('placeholder', 'Sexe');

// Ceci fournit le style de l'élément  bouton de soumission:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');


$form->setAttribute('action', $this->url('client', ['action' => 'add']));
$form->prepare();
echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($nom) ?>
        <?= $this->formElement($nom) ?>
        <?= $this->formElementErrors()->render($nom, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($prenom) ?>
        <?= $this->formElement($prenom) ?>
        <?= $this->formElementErrors()->render($prenom, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($adresse) ?>
        <?= $this->formElement($adresse) ?>
        <?= $this->formElementErrors()->render($adresse, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($email) ?>
        <?= $this->formElement($email) ?>
        <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($date_naissance) ?>
        <?= $this->formElement($date_naissance) ?>
        <?= $this->formElementErrors()->render($date_naissance, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($sexe) ?>
        <?= $this->formElement($sexe) ?>
        <?= $this->formElementErrors()->render($sexe, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag(); 