<?php
// module/Client/view/client/client/add.phtml:

$title = 'Ajouter un article';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
// Ceci fournit le style de l'élément  nom:
$designation = $form->get('designation');
$designation->setAttribute('class', 'form-control');
$designation->setAttribute('placeholder', 'Designation du produit');

// Ceci fournit le style de l'élément  prnom:
$prix_unit = $form->get('prix_unit');
$prix_unit->setAttribute('class', 'form-control');
$prix_unit->setAttribute('placeholder', 'Prix unitaire');



// Ceci fournit le style de l'élément  bouton de soumission:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');


$form->setAttribute('action', $this->url('article', ['action' => 'add']));
$form->prepare();
echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($designation) ?>
        <?= $this->formElement($designation) ?>
        <?= $this->formElementErrors()->render($designation, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($prix_unit) ?>
        <?= $this->formElement($prix_unit) ?>
        <?= $this->formElementErrors()->render($prix_unit, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag(); 