<?php
// module/Client/view/client/client/delete.phtml:

$title = 'Suppression d\'un article';
$url   = $this->url('article', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Etes-vous sûr de vouloir supprimer
    "<?= $this->escapeHtml($article->designation) ?>"?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $article->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Oui" />
    <input type="submit" class="btn btn-success" name="del" value="Non" />
</div>
</form> 