<?php
// module/Client/view/client/client/index.phtml:

$title = 'Mes articles';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('article', ['action' => 'add']) ?>">Ajouter un article</a>
</p>

<table class="table striped">
<tr>
    <th>Designation</th>
    <th>Prix unitaire</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($paginator as $article) : ?>
    <tr>
        <td><?= $this->escapeHtml($article->designation) ?></td>
        <td><?= $this->escapeHtml($article->prix_unit) ?></td>

        <td>
            <a href="<?= $this->url('article', ['action' => 'edit', 'id' => $article->id]) ?>">Modifier</a>
            <a href="<?= $this->url('article', ['action' => 'delete', 'id' => $article->id]) ?>">Supprimer</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<?= $this->paginationControl(
        $this->paginator,
        'sliding',
        'partial/paginator',
        ['route' => 'article']
) ?>